version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app    #replace -v $(pwd):/app
      -  /app/node_modules        #replace -v /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=database-mongo
      - MONGO_PASSWORD=123456
      - SESSION_SECRET=secret
    command: npm run dev
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=database-mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456