version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app    #replace -v $(pwd):/app
      -  /app/node_modules        #replace -v /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
